Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu-1204-server-32"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.synced_folder "~/webapp", "/opt/webapp", :nfs => true
    config.vm.network :private_network, ip: "33.33.33.10"

    ## Use all the defaults:
    config.vm.provision :ansible do |ansible|
        ansible.playbook = "../site.yml"
        ansible.inventory_file = "../development"
        ansible.verbose = true
    end
end
